# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com

before_install:
  - ./test/customize_environment.sh

install:
  - ./src/os/setup.sh -y

language: generic

script:
  - ./test/main.sh

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      env:
        - INSTALL_APPLICATION_IF_READABLE_NAME_MATCH_REGEX="^([a-jA-J0-9]|Bash|Java).*$"
    - os: osx
      osx_image: xcode7.3
      env:
        - INSTALL_APPLICATION_IF_READABLE_NAME_MATCH_REGEX="^([h-zH-Z]|Bash|Java).*$"
