# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com

before_install:
  - ./test/customize_environment.sh

install:
  - ./src/os/setup.sh -y

language: generic

script:
  - ./test/main.sh

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3
