# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com

before_install:
  - ./test/customize_environment.sh

install:
  - ./src/os/setup.sh -y

language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env:
        - INSTALL_APPLICATION_IF_READABLE_NAME_MATCH_REGEX="^([a-fA-F0-9]|Bash|Java).*$"
    - os: osx
      osx_image: xcode9.2
      env:
        - INSTALL_APPLICATION_IF_READABLE_NAME_MATCH_REGEX="^([g-pG-P]|Bash|Java).*$"
    - os: osx
      osx_image: xcode9.2
      env:
        - INSTALL_APPLICATION_IF_READABLE_NAME_MATCH_REGEX="^([q-zQ-Z]|Bash|Java).*$"

script:
  - ./test/main.sh

sudo: required
