# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com

before_install:
  - |
      # Install `ShellCheck`.
      #
      # ShellCheck is required for testing and
      # is included with Travis's Ubuntu builds,
      # so it only needs to be installed for the
      # macOS ones.
      if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew install shellcheck
      fi
#before_install:
#  - ./test/customize_environment.sh
#
#install:
#  - ./src/os/setup.sh -y

language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode11
      env:
        - INSTALL_APPLICATION_IF_READABLE_NAME_MATCH_REGEX="^([a-fA-F0-9]|Bash|Java).*$"
    - os: osx
      osx_image: xcode11
      env:
        - INSTALL_APPLICATION_IF_READABLE_NAME_MATCH_REGEX="^([g-pG-P]|Bash|Java).*$"
    - os: osx
      osx_image: xcode11
      env:
        - INSTALL_APPLICATION_IF_READABLE_NAME_MATCH_REGEX="^([q-zQ-Z]|Bash|Java).*$"

script:
  - ./test/run_shellcheck.sh
#script:
#  - ./test/main.sh

sudo: required
