#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Set LSCOLORS (FreeBSD / OS X)
#
#  - `ls` displays colors if the `-G` option is passed or if
#    the `CLICOLOR` environment variable is set
#
#  - the actual colors are configured through the `LSCOLORS`
#    environment variable (built-in defaults are used if this
#    variable is not set)
#
# - The order of each two characters determines components
# - The first character is the foreground colour
# - The second character is the background colour
# See REFERENCE-LC-COLOURS.md

LSCOLORS=""

LSCOLORS+="gx" # Directory
LSCOLORS+="fx" # Symbolic link
LSCOLORS+="cx" # Socket
LSCOLORS+="dx" # Pipe
LSCOLORS+="cx" # Executable
LSCOLORS+="eg" # Block special
LSCOLORS+="ed" # Character special
LSCOLORS+="ab" # Executable with setuid bit set
LSCOLORS+="ag" # Executable with setgid bit set
LSCOLORS+="cc" # Directory writable to others, with sticky bit
LSCOLORS+="bd" # Directory writable to others, without sticky bit

# Use http://geoff.greer.fm/lscolors/ to preview gxfxcxdxcxegedabagccbd
export LSCOLORS

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Enable color support

alias ls="ls -G" # or CLICOLOR=1
