#!/bin/bash

# -f : True if file exists and is a regular file.
if [ -f "$(brew --prefix)/share/bash-completion/bash_completion" ]; then

    # Use `bash-completion` 2.x
    source "$(brew --prefix)/share/bash-completion/bash_completion"

    # Make Bash complete the `g` alias just like it does `git`
    # https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion-Builtins.html
    complete -o default -o nospace -F _git g

fi
