#!/usr/bin/env bash

# -f : True if file exists and is a regular file.
if  [ -f "$(brew --prefix)/etc/profile.d/z.sh" ]; then
    # Load rupa's z (https://github.com/rupa/z) if installed
    source "$(brew --prefix)/etc/profile.d/z.sh"
fi
