#!/usr/bin/env bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias cp="cp -iv"
#             │└─ list copied files
#             └─ prompt before overwriting an existing file

alias mkdir="mkdir -pv"
#                   │└─ list created directories
#                   └─ create intermediate directories

alias mv="mv -iv"
#             │└─ list moved files
#             └─ prompt before overwriting an existing file

alias rm="rm -rf --"
#                └─ to indicate end of options in case filename starts with -

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"                      # clear history
alias d="cd ~/Desktop"                                          # change working directory to ~/Desktop
alias e="vim --"                                                # -- to indicate end of options in case filename starts with -
alias g="git"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"   # myip.opendns.com: name of resource record to lookup, @resolver1.opendns.com: name server to query
                                                                # This asks the IP address of myip.opendns.com from the name server resolver1.opendns.com
                                                                # which will return your external IP address
alias ll="ls -l"
alias m="man"
alias map="xargs -n1"                                           # map space delimited string to one item per row. Only enter input afterwards
                                                                # See http://www.thegeekstuff.com/2013/12/xargs-examples/

alias mrmp="mrm --preset @wingy3181/mrm-preset-wingy3181"
alias n="npm"
alias nr="npm run"
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias hosts='sudo $EDITOR /etc/hosts'                           # Open hosts file in default editor
alias scrcpyw="setup-scrcpy"
alias ssh="sshrc"
alias t="tmux"
alias y="yarn"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases.

. "$OS/bash_aliases"
