#!/usr/bin/env bash

# [!] Do not rename this file to `bash_completion`
#     as it will create an infinite loop!

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

. "$OS/bash_autocomplete"
