#!/usr/bin/env bash

# http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html
#  .bash_profile is executed for login shells, while .bashrc is executed for interactive non-login shells (e.g. subshells).
#  When you login (type username and password) via console, either sitting at the machine, or remotely via
#  ssh: .bash_profile is executed to configure your shell before the initial command prompt.

# - n : True if the length of string is nonzero.
# PS1 : Prompt String 1
[ -n "$PS1" ] \
    && . "$HOME/.bash_profile"
