#!/bin/bash

declare DOTFILES_DIR_PATH="$(dirname "$(dirname "$(readlink "${BASH_SOURCE[0]}")")")"

source "$DOTFILES_DIR_PATH/os/utils.sh" \
    && declare os="$(get_os)"

# ----------------------------------------------------------------------

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"                      # clear history
alias e="vim --"                                                # -- to indicate end of options in case filename starts with -
alias g="git"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"   # myip.opendns.com: name of resource record to lookup, @resolver1.opendns.com: name server to query
                                                                # This asks the IP address of myip.opendns.com from the name server resolver1.opendns.com
                                                                # which will return your external IP address
alias ll="ls -l"
alias m="man"
alias map="xargs -n1"                                           # map space delimited string to one item per row. Only enter input afterwards
                                                                # See http://www.thegeekstuff.com/2013/12/xargs-examples/
alias n="npm"
alias q="exit"
alias rm="rm -rf --"                                            # -- to indicate end of options in case filename starts with -
alias hosts='sudo $EDITOR /etc/hosts'                           # Open hosts file in default editor

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases

if [ "$os" == "osx" ]; then
    source "$DOTFILES_DIR_PATH/shell/os_x/bash_aliases"
elif [ "$os" == "ubuntu" ]; then
    source "$DOTFILES_DIR_PATH/shell/ubuntu/bash_aliases"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Cleanup

unset DOTFILES_DIR_PATH
unset os
