#!/usr/bin/env bash


# Bash Variables.
# https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html
#
#   History Variables
#   http://jorge.fbarr.net/2011/03/24/making-your-bash-history-more-efficient/
#
#   Locale Variables
#   http://www.shellhacks.com/en/HowTo-Change-Locale-Language-and-Character-Set-in-Linux

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Make vim the default editor.
export EDITOR="vim"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Ignore commands that start with spaces and duplicates.

export HISTCONTROL=ignoreboth

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Increase the maximum number of lines of history
# persisted in the history file (default value is 500).

export HISTFILESIZE=10000

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Don't add certain commands to the history file.

export HISTIGNORE="&:[bf]g:c:clear:history:exit:q:pwd:* --help"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Increase the maximum number of commands recorded
# in the command history (default value is 500).

export HISTSIZE=10000

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Prefer US English and use UTF-8 encoding.

export LANG="en_AU"
export LC_ALL="en_AU.UTF-8"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Use custom `less` colors for `man` pages.
# https://www.gnu.org/software/termutils/manual/termutils-2.0/html_chapter/tput_1.html
# https://gist.github.com/supermarin/6dca255da372c3f9eb26
# https://wiki.archlinux.org/index.php/man_page#Colored_man_pages
# https://linuxtidbits.wordpress.com/2009/03/23/less-colors-for-man-pages/
export LESS_TERMCAP_md=$'\e[1;32m'   # begin bold mode (green). See http://www.bashguru.com/2010/01/shell-colors-colorizing-shell-scripts.html
export LESS_TERMCAP_me=$'\e[0m'      # end bold mode.
#export LESS_TERMCAP_us=$'\e[4;32m'   # begin underscore mode.
#export LESS_TERMCAP_ue=$'\e[0m'      # end underscore mode.

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Don't clear the screen after quitting a `man` page.

export MANPAGER="less -X"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Increase the maximum number of lines of history persisted
# in the `Node` REPL history file (default value is 1000).
#
# https://github.com/nodejs/node/blob/c948877688ff2b6a37f2c88724b656aae495c7b2/doc/api/repl.md#persistent-history

export NODE_REPL_HISTORY_SIZE=10000

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# PROMPT_COMMAND = command that is executed just before bash displays a prompt
# See http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/x264.html
# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history.
# See https://www.gnu.org/software/bash/manual/html_node/Bash-History-Builtins.html

export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Make Python use UTF-8 encoding for output to stdin/stdout/stderr.

export PYTHONIOENCODING="UTF-8"
