#!/usr/bin/env bash

# Hook zoxide into bash shell
# See:
# - https://github.com/ajeetdsouza/zoxide#installation
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

eval "$(zoxide init bash)"
