#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Simple Calculator

? () {

    local result=""

    #                       ┌─ default (when --mathlib is used) is 20
    result="$( printf "scale=10;%s\n" "$*" | bc --mathlib | tr -d "\\\n" )"
    #                         remove the tailing "\" and "\n" ─┘
    #                         (large numbers are printed on multiple lines)
    # See https://www.gnu.org/software/bc/manual/html_node/bc_toc.html

    if [[ "$result" == *.* ]]; then
        # Improve the output for decimal numbers
        printf "%s" "$result" |
        sed -e "s/^\./0./"          # add "0" for cases like ".5"` \
            -e "s/^-\./-0./"        # add "0" for cases like "-.5"`\
            -e "s/0*$//;s/\.$//"    # remove tailing zeros
    else
        printf "%s" "$result"
    fi

    printf "\n"

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Create data URI from a file

datauri() {
    # $1 : file to generate data uri for
    local mimeType=""
    # True if file exists and is a regular file.
    if [ -f "$1" ]; then
        mimeType=$(file -b --mime-type "$1")
        #                └─ do not prepend the filename to the output

        if [[ $mimeType == text/* ]]; then
            mimeType="$mimeType;charset=utf-8"
        fi

        printf "data:%s;base64,%s" \
                    "$mimeType" \
                    "$(openssl base64 -in "$1" | tr -d "\n")"
        #                │       │                │  └── Delete characters in string argument from string passed in
        #                │       │                └── translate characters command
        #                │       └── base64 encode file
        #                └── convert input text to open ssl format? (technically this isn't actually needed)
    else
        printf "%s is not a file.\n" "$1"
    fi

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Delete files that match a certain pattern from the current directory
# This lists the files deleted via the -ls option

delete-files() {
    # $1 : file pattern to search for files to delete
    local q="${1:-*.DS_Store}"
    find . -type f -name "$q" -ls -delete
    #    |       |         |   |   └─── delete found files (or directories)
    #    │       │         │   └─── list file information
    #    │       │         └─── pattern of filename to search for
    #    │       └──── search for files
    #    └────── current directory to recursively traverse to find files
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Get gzip information (gzipped file size + reduction size)

gz() {
    # $1 : file to get gzip information from

    # declare integers
    declare -i gzippedSize=0
    declare -i originalSize=0

    # -f: True if file exists and is a regular file.
    if [ -f "$1" ]; then
        # -s : True if file exists and has a size greater than zero.
        if [ -s "$1" ]; then

            originalSize=$( wc -c < "$1" )
            # %12s\n : 12 chars long, convert to string, append \n
            # See http://en.cppreference.com/w/cpp/io/c/fprintf
            printf "\n original size:   %12s\n" "$(hrfs "$originalSize")"

            # gzip -c to standard output
            gzippedSize=$( gzip -c "$1" | wc -c )
            printf " gzipped size:    %12s\n" "$(hrfs "$gzippedSize")"

            printf " ─────────────────────────────\n"
            printf " reduction:       %12s [%s%%]\n\n" \
                        "$( hrfs $((originalSize - gzippedSize)) )" \
                        "$( printf "%s %s" "$originalSize $gzippedSize" | \
                            awk '{ printf "%.1f", 100 - $2 * 100 / $1 }' | \
                            sed -e "s/0*$//;s/\.$//" )"
                            #              └─ remove tailing zeros

        else
            printf "\"%s\" is empty.\n" "$1"
        fi
    else
        printf "\"%s\" is not a file.\n" "$1"
    fi

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Human readable file size
# (because `du -h` doesn't cut it for me)

hrfs() {
    # $1 : number to convert to file size

    printf "%s" "$1" |
    awk '{
            i = 1;
            split("B KB MB GB TB PB EB ZB YB WTFB", v);
            value = $1;

            # confirm that the input is a number
            if ( value + .0 == value ) {

                while ( value >= 1024 ) {
                    value/=1024;
                    i++;
                }

                if ( value == int(value) ) {
                    printf "%d %s", value, v[i]
                } else {
                    printf "%.1f %s", value, v[i]
                }

            }
        }' |
    sed -e ":l" -e "s/\([0-9]\)\([0-9]\{3\}\)/\1,\2/" -e "t l"
    #                             └─ add commas to the numbers
    #                                (changes "1023.2 KB" to "1,023.2 KB")
    # See http://www.grymoire.com/Unix/Sed.html
    # -e  : combine multiple commands by using -e before each command
    # :l  : create label
    # t l : execute code at label if a pattern match is found
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Create new directories and enter the first one

mkd() {
    # $* : arguments passed to mkd which is the directories to create
    # -n : True if the length of string is nonzero.
    if [ -n "$*" ]; then

        mkdir -p "$@"
        #      └─ make parent directories if needed

        cd "$@" \
            || exit 1

    fi
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Search history

qh() {
    # $* : arguments passed to qh which is the search text
    # HISTFILE : https://www.gnu.org/software/bash/manual/html_node/Bash-History-Facilities.html
    #
    #           ┌─ enable colors for pipe
    #           │  ("--color=auto" enables colors only if
    #           │  the output is in the terminal)
    grep --color=always "$*" "$HISTFILE" |       less -RX
    # display ANSI color escape sequences in raw form ─┘│
    #       don't clear the screen after quitting less ─┘
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Search for text within the current directory

qt() {
    # $* : arguments passed to qt which is the search text
    grep -ir --color=always "$*" . | less -RX
    #     │└─ search all files under each directory, recursively
    #     └─ ignore case
}


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Start an HTTP server from a directory, optionally specifying the port
# $1 : Port to start server on (defaults to 8000)

server() {

    declare -r MAX_NUMBER_OF_TRIES=10
    local i=0
    local port="${1:-8000}"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Wait for the server to be available, and once
    # it is, open its address in the default browser

    while [ $i -lt $MAX_NUMBER_OF_TRIES ]; do
        # lsof : list open files (and remember, in UNIX just about everything (including a network socket) is a file)
        #   -i : select the listing of all Internet and x.25 (HP-UX) network files
        #   -n : inhibit conversion of network number to host names for network files
        #   -P : inhibit conversion of port number to port name for network files
        # grep -i : ignore case
        if [ "$(lsof -i -nP | grep "$port" | grep -i "python")" != "" ]; then
            o "http://localhost:${port}/"
            break;
        fi
        i=$(( i + 1 ))
        sleep 1 # sleep 1 second
    done &

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Start server
    # - c: code to execute (See https://docs.python.org/2/using/cmdline.html)
    python -c "

import sys

try:
    import SimpleHTTPServer as server
    import SocketServer as socketserver
except ImportError:

    # In Python 3, the 'SimpleHTTPServer'
    # module has been merged into 'http.server'

    import http.server as server
    import socketserver

handler = server.SimpleHTTPRequestHandler
map = handler.extensions_map
port = int(sys.argv[1])

# Set default Content-Type to 'text/plain'
map[''] = 'text/plain'

# Serve everything as UTF-8 (although not technically
# correct, this doesn't break anything for binary files)
for key, value in map.items():
    map[key] = value + '; charset=utf-8'

# Create, but don't automatically bind socket
# (the 'allow_reuse_address' option needs to be set first)
httpd = socketserver.ThreadingTCPServer(('localhost', port), handler, False)

# Prevent 'cannot bind to address' errors on restart
# https://brokenbad.com/address-reuse-in-pythons-socketserver/
httpd.allow_reuse_address = True

# Manually bind socket and start the server
httpd.server_bind()
httpd.server_activate()
print('Serving content on port:', port)
httpd.serve_forever()

    " "$port"

}
