#!/usr/bin/env bash

# Rupa's Z - Jump to - (https://github.com/rupa/z)
# - Consider reusing your current .z file if possible. it's painful to rebuild :)
# - z is hooked up in .bash_profile

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

declare DOTFILES_DIR_PATH="$(dirname "$(dirname "$(readlink "${BASH_SOURCE[0]}")")")"

. "$DOTFILES_DIR_PATH/os/utils.sh" \
    && declare os="$(get_os)"

# ----------------------------------------------------------------------

. "$DOTFILES_DIR_PATH/shell/$os/bash_z"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Cleanup

unset DOTFILES_DIR_PATH
unset os
