#!/usr/bin/env bash

# Readline library configuration options
# http://ss64.com/bash/syntax-inputrc.html

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Enable beeping and window flashing
# 'none', 'audible', 'visible'
set bell-style audible

# Use case-insensitive TAB autocompletion
set completion-ignore-case on

# Auto list TAB completions
# This will allow single tab completion as opposed to requiring a double tab. This makes things much more pleasant, in my opinion.
set show-all-if-ambiguous on
