#!/usr/bin/env bash

# Readline library configuration options
# http://ss64.com/bash/syntax-inputrc.html

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Enable beeping and window flashing
# 'none', 'audible', 'visible'
set bell-style audible

# Use case-insensitive TAB autocompletion
set completion-ignore-case on

# Auto list TAB completions
# This will allow single tab completion as opposed to requiring a double tab. This makes things much more pleasant, in my opinion.
set show-all-if-ambiguous on

# https://stackoverflow.com/questions/1030182/how-do-i-change-bash-history-completion-to-complete-whats-already-on-the-line
"\e[A": history-search-backward            # arrow up
"\e[B": history-search-forward             # arrow down