#!/usr/bin/env bash

# Readline library configuration options.
# http://ss64.com/bash/syntax-inputrc.html

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# If there are multiple matches for completion,
# make TAB cycle through them.

TAB: menu-complete

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Searching files via partial match.
# https://stackoverflow.com/questions/1030182/how-do-i-change-bash-history-completion-to-complete-whats-already-on-the-line
# ↑
"\e[A":history-search-backward
# ↓
"\e[B":history-search-forward

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Enable beeping and window flashing.
# 'none', 'audible', 'visible'

set bell-style audible

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Use case-insensitive TAB autocompletion.

set completion-ignore-case on

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Perform partial completion on the first Tab press, and
# only start cycling full results on the second Tab press.

set menu-complete-display-prefix on

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Display a list of the matching files

set show-all-if-ambiguous on
