#!/usr/bin/env bash

declare -r BASH_COMPLETION_PATH="$(brew --prefix 2> /dev/null)/share/bash-completion/bash_completion"

# -f : True if file exists and is a regular file.
if [ -f "$BASH_COMPLETION_PATH" ]; then

    # Use the latest `bash-completion`.

    . "$BASH_COMPLETION_PATH"

    # Make Bash complete the `g` alias just like it does `git`.
    # https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion-Builtins.html

    complete -o default -o nospace -F _git g

fi
