# For more information about the configurations used
# in this file, please see the GitHub Actions documentation.
#
# https://docs.github.com/en/actions
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

jobs:
  macOS:
    runs-on: macos-latest

    steps:
      - name: Output Inputs
        run: echo '${{ toJSON(github.event.inputs) }}'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install some applications
        env:
          INSTALL_APPLICATION_IF_READABLE_NAME_MATCH_REGEX: ${{ inputs.applicationsToInstall }}
          SHOW_SPINNER_ON_CI: ${{ inputs.showSpinnerOnCI }}
          TERM: xterm-256color
        run: ./src/os/setup.sh -y

name: Install some applications

on:
  workflow_dispatch:
    inputs:
      applicationsToInstall:
        description: 'Applications to install (whitelisted regex)'
        required: true
        default: '^(Chrome).*$'
        type: string
      showSpinnerOnCI:
        description: 'Show the execution spinner on CI'
        required: false
        default: false
        type: boolean
